title: Nexus News in Focus
remote_theme: opendocsg/opendoc-theme
timezone: Asia/Singapore
repository: opendocsg/opendoc-nexus-news-in-focus
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

folders:
  - name: 'issue_2_20'
    title: 'Issue 2/2020'
    order:
      - main.md
  - name: 'issue_3_20'
    title: 'Issue 3/2020'
    order:
      - main.md
styling_options:
  primary_brand_color: '#c00000'  #----> Optional, theme color
  logo_path: /assets/logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5cee3d46138e3200109244df #----> Optional, feedback url
